# Generated by Django 5.0.6 on 2024-06-15 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_prodcut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodcut',
            new_name='Product',
        ),
    ]
