# Generated by Django 5.0.6 on 2024-06-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_qty',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
